In [1]:
import numpy as np
np.arange(10)


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [2]:
array_1 = np.arange(10)
array_1.shape

(10,)

In [14]:
array_1=array_1.reshape((5,2))

In [10]:
array_1.ndim

2

In [15]:
array_1+1

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [16]:
array_2=np.arange(10)
array_2*array_2

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [17]:
np.empty((5,2),dtype=np.float)

array([[0.00000000e+000, 0.00000000e+000],
       [6.92700572e-310, 6.92700830e-310],
       [6.92700565e-310, 2.47032823e-323],
       [6.08419434e-310, 6.92700619e-310],
       [4.94065646e-324, 7.80312086e-309]])

In [18]:
array_1[0,0]

0

In [21]:
array_1=array_1+1

In [28]:
array_1[:,]

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [29]:
array_1>5

array([[False, False],
       [False, False],
       [False,  True],
       [ True,  True],
       [ True,  True]])

In [36]:
array_1[4]

array([ 9, 10])