In [1]:
import numpy as np
X = np.array([[1, 2], [3, 4], [5, 6], [7, 8],[1, 2], [3, 4], [5, 6], [7,8]])
y = np.array([1, 2, 1, 2, 1, 2, 1, 2])


In [4]:
from sklearn.model_selection import KFold 
kf= KFold(n_splits = 4)
kf

KFold(n_splits=4, random_state=None, shuffle=False)

In [3]:
cc = 1
for train_index, test_index in kf.split(X):
      print ("Round : ",cc,": "),
      print ("Training indices :", train_index),
      print ("Testing indices :", test_index)
      cc += 1

Round :  1 : 
Training indices : [2 3 4 5 6 7]
Testing indices : [0 1]
Round :  2 : 
Training indices : [0 1 4 5 6 7]
Testing indices : [2 3]
Round :  3 : 
Training indices : [0 1 2 3 6 7]
Testing indices : [4 5]
Round :  4 : 
Training indices : [0 1 2 3 4 5]
Testing indices : [6 7]


In [24]:
X

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8],
       [1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [16]:
kf.get_n_splits()

4

In [17]:
indices_list = list(kf.split(X))

In [19]:
indices_list

[(array([2, 3, 4, 5, 6, 7]), array([0, 1])),
 (array([0, 1, 4, 5, 6, 7]), array([2, 3])),
 (array([0, 1, 2, 3, 6, 7]), array([4, 5])),
 (array([0, 1, 2, 3, 4, 5]), array([6, 7]))]

In [22]:
train_indices, test_indices = indices_list[3]
train_indices

array([0, 1, 2, 3, 4, 5])

In [23]:
test_indices

array([6, 7])

In [21]:
X[train_indices]


array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8],
       [1, 2],
       [3, 4]])

In [30]:
y[train_indices]

array([1, 2, 1, 2, 1, 2])

In [31]:
X[test_indices]

array([[5, 6],
       [7, 8]])

In [32]:
y[test_indices]

array([1, 2])