In [1]:
from sklearn.model_selection import TimeSeriesSplit
import numpy as np
X = np.array([[1, 2], [3, 4], [1, 2], [3, 4],[1, 2], [3, 4], [1, 2], [3,4]])
y = np.array([1, 2, 3, 4, 1, 2, 3, 4])


In [2]:
tscv = TimeSeriesSplit(n_splits=7)

In [3]:
for train_index, test_index in tscv.split(X):
  X_train, X_test = X[train_index], X[test_index]
  y_train, y_test = y[train_index], y[test_index]
  print ("Training indices:", train_index, "Testing indices:",test_index)

Training indices: [0] Testing indices: [1]
Training indices: [0 1] Testing indices: [2]
Training indices: [0 1 2] Testing indices: [3]
Training indices: [0 1 2 3] Testing indices: [4]
Training indices: [0 1 2 3 4] Testing indices: [5]
Training indices: [0 1 2 3 4 5] Testing indices: [6]
Training indices: [0 1 2 3 4 5 6] Testing indices: [7]


In [4]:
tscv_list = list(tscv.split(X))

In [5]:
tscv_list

[(array([0]), array([1])),
 (array([0, 1]), array([2])),
 (array([0, 1, 2]), array([3])),
 (array([0, 1, 2, 3]), array([4])),
 (array([0, 1, 2, 3, 4]), array([5])),
 (array([0, 1, 2, 3, 4, 5]), array([6])),
 (array([0, 1, 2, 3, 4, 5, 6]), array([7]))]