In [1]:
import numpy as np
from sklearn.datasets import make_blobs
blobs, labels = make_blobs(int(1e6), 3)

In [2]:
from sklearn.cluster import KMeans, MiniBatchKMeans

In [3]:
kmeans = KMeans(n_clusters=3)
minibatch = MiniBatchKMeans(n_clusters=3)

In [4]:
%time kmeans.fit(blobs) #IPython Magic

CPU times: user 2.73 s, sys: 341 ms, total: 3.07 s
Wall time: 3.1 s


KMeans(n_clusters=3)

In [6]:
KMeans(algorithm='auto', copy_x=True, init='k-means++',
     max_iter=300,
         n_clusters=3, n_init=10,
         random_state=None, tol=0.0001, verbose=0)

KMeans(n_clusters=3)

In [7]:
%time minibatch.fit(blobs)

CPU times: user 653 ms, sys: 141 ms, total: 794 ms
Wall time: 849 ms


MiniBatchKMeans(n_clusters=3)

In [9]:
MiniBatchKMeans(batch_size=100, compute_labels=True, init='k-means++',
             init_size=None, max_iter=100, max_no_improvement=10,
     n_clusters=3,
             n_init=3, random_state=None, reassignment_ratio=0.01,
     tol=0.0,
verbose=0)

MiniBatchKMeans(batch_size=100, n_clusters=3)

In [10]:
minibatch.cluster_centers_

array([[-0.79960572, -8.6291273 , -6.05741336],
       [ 8.46279759,  8.90792278,  3.53970779],
       [ 4.79625737, -0.58410061,  8.03493902]])

In [11]:
kmeans.cluster_centers_

array([[ 8.46826887,  8.91333971,  3.53987839],
       [-0.80104645, -8.6268592 , -6.05590021],
       [ 4.79641561, -0.58353292,  8.03400832]])

In [12]:
from sklearn.metrics import pairwise

In [13]:
pairwise.pairwise_distances(kmeans.cluster_centers_[0].reshape(1,
            -1), minibatch.cluster_centers_[0].reshape(1, -1))

array([[22.0395022]])

In [14]:
np.diag(pairwise.pairwise_distances(kmeans.cluster_centers_,
            minibatch.cluster_centers_))

array([2.20395022e+01, 2.20309573e+01, 1.10159820e-03])

###  the oder of the clusters is different which is why the pairwise calculated distances are large for the first two

In [15]:
minibatch = MiniBatchKMeans(batch_size=len(blobs))
%time minibatch.fit(blobs)

CPU times: user 17 s, sys: 1.07 s, total: 18.1 s
Wall time: 9.2 s


MiniBatchKMeans(batch_size=1000000)

In [16]:
MiniBatchKMeans(batch_size=1000000, compute_labels=True, init='k-means++',
           init_size=None, max_iter=100, max_no_improvement=10, n_clusters=8,
           n_init=3, random_state=None, reassignment_ratio=0.01, tol=0.0,
           verbose=0)

MiniBatchKMeans(batch_size=1000000)